# Generated by Django 4.0.9 on 2023-02-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('holder', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('locked', models.BooleanField()),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
