# Generated by Django 4.0.9 on 2023-02-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
